import Navbar from './Navbar';

const Header = () => {
  return (
    <>
      <header>
        <title>Para cuando?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      <Navbar />
    </>
  );
};

export default Header;
